= Upgrading Cloudflow
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::ROOT:partial$include.adoc[]

Upgrading Cloudflow after a new release is done using the Helm upgrade command, the command will upgrade Cloudflow to the latest version.

	helm upgrade cloudflow cloudflow-helm-charts/cloudflow --namespace cloudflow --set cloudflow_operator.persistentStorageClass=nfs --set cloudflow_operator.kafkaBootstrapservers=cloudflow-strimzi-kafka-bootstrap.cloudflow:9092

To upgrade Cloudflow to a specific version, add the _--version_ flag. For example:

	helm upgrade cloudflow cloudflow-helm-charts/cloudflow --namespace cloudflow --set cloudflow_operator.persistentStorageClass=nfs --set cloudflow_operator.kafkaBootstrapservers=cloudflow-strimzi-kafka-bootstrap.cloudflow:9092 --version="2.0.8"

IMPORTANT: A typical upgrade of Cloudflow does not affect the running Cloudflow applications. However, it is essential to make sure to read the release notes to make sure there are no breaking changes.