# https://github.com/actions/labeler
documentation:
  - 'docs/**/*'
examples:
  - 'examples/**/*'

akka:
  - 'core/cloudflow-akka/**/*'
  - 'core/cloudflow-akka-tests/**/*'
  - 'core/cloudflow-akka-util/**/*'
flink:
  - 'core/cloudflow-flink/**/*'
  - 'core/cloudflow-flink-testkit/**/*'
  - 'core/cloudflow-flink-tests/**/*'
spark:
  - 'core/cloudflow-spark/**/*'
  - 'core/cloudflow-spark-testkit/**/*'
  - 'core/cloudflow-spark-tests/**/*'
operator:
  - 'core/cloudflow-operator/**/*'
streamlets:
  - 'core/cloudflow-streamlets/**/*'
dependencies:
  - 'core/project/Dependencies.scala'

kubectl-cloudflow:
  - 'kubectl-cloudflow/**/*'
