:page-partial:
:page-supergroup-scala-java: Language

include::ROOT:partial$include.adoc[]

The `cloudflow.akka.util` library contains some predefined `StreamletLogic`{empty}s:

- <<akka-http-streamlet.adoc#,HttpServerLogic>>
- <<akka-grpc-streamlet.adoc#,HttpServerLogic>>
- `Splitter`
- `Merger`

The following sections describe how you implement stream processing logic with these utilities.

== Splitter

=== Use case

A `Splitter` can be used to split a stream in two, writing elements to one of two outlets.
Every element from the outlet will be processed through a `FlowWithCommittableContext`, which provides at-least-once semantics.

=== Example

The `Splitter` defines a `sink` method for the user to supply a `FlowWithCommittableContext[I, Either[L, R]]` and a `left` and `right` outlet.
The Java version of `Splitter` uses an `Either` type that is bundled with cloudflow as `cloudflow.akka.javadsl.util.Either`.

The examples below shows a `Splitter` that validates metrics and splits the stream into valid and invalid metrics, which are written respectively to the `valid` and `invalid` outlets:

[.tabset]
Scala::
+
[source,scala]
----
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-scala/src/main/scala/cloudflow/akkastreamsdoc/DataSplitter.scala[tag=splitter]
----

Java::
+
[source,java]
----
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-java/src/main/java/cloudflow/akkastreamsdoc/DataSplitter.java[tag=splitter]
----

== Merger

=== Use case

A `Merger` can be used to merge two or more inlets into one outlet.

Elements from all inlets will be processed with at-least-once semantics. The elements will be processed in semi-random order and with equal priority for all inlets.

=== Example

The examples below shows how to use a `Merger.source` to combine elements from two inlets of the type `Metric` into one outlet of the same type.

[.tabset]
Scala::
+
[source,scala]
----
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-scala/src/main/scala/cloudflow/akkastreamsdoc/DataMerge.scala[tag=merge]
----

Java::
+
[source,java]
----
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-java/src/main/java/cloudflow/akkastreamsdoc/DataMerge.java[tag=merge]
----
