:page-partial:

include::ROOT:partial$include.adoc[]

A streamlet can be configured when it is deployed with `kubectl cloudflow deploy` or re-configured with `kubectl cloudflow configure`. 
These commands deploy or restart streamlets as necessary.

Configuration values can be set for all streamlets of a particular runtime at once, or they can be set for a specific streamlet.

You can configure the following items for a streamlet:

    - Streamlet Configuration Parameters
    - Kubernetes container resource requirements
    - Runtime settings (for Akka, Spark, Flink, or any user-provided one)
​
The configuration can be specified via file arguments or passed directly on the command line.

== Configuring a Streamlet using Configuration Files

Let's look at an example of passing a configuration file to the deploy command:

[source, bash]
----
$ {cli-plugin} cloudflow deploy target/my-app.json --conf my-config.conf
----

In the above example the `my-app` application is deployed with a `my-config.conf` configuration file.

Configuration files are merged by concatenating the files passed with `--conf` flags. 
The last `--conf [file]` argument can override values specified in earlier `--conf [file]` arguments.
In the example below, where the same configuration path is used in `file1.conf` and `file2.conf`, 
the configuration value in `file2.conf` takes precedence, overriding the value provided by `file1.conf`:

[source, bash]
----
$ {cli-plugin} cloudflow deploy swiss-knife.json --conf file1.conf --conf file2.conf
----

== Configuring File Format

Configuration files must follow the https://github.com/lightbend/config/blob/master/HOCON.md[HOCON] format. 
The configuration for a streamlet must be specified in a `cloudflow.streamlets.[streamlet-name]` section.
This section can optionally contain three sections to configure the following: 

     - Streamlet configuration parameters
     - Kubernetes container settings
     - Runtime settings.

The example below shows the structure:

[source, hocon]
----
cloudflow {
  streamlets {
    my-streamlet {
      config-parameters {
        // config parameter values go here  
        my-config-parameter = "some-value"
      }  
      config {
        // runtime settings go here
        akka.loglevel = "DEBUG"
      }
      kubernetes {
        pods.pod.containers.container {
          // kubernetes container settings go here  
          resources {
            requests {
              memory = "512M"
            }
            limits {
              memory = "1024M"
            }
          }
        }
      }
    }    
  } 
}
----
You need to specify at least one of the sections shown above, in `cloudflow.streamlets.[streamlet-name]`. 
Configuration for all streamlets of a runtime can be specified in a `cloudflow.runtimes.[runtime].config` section.
The configuration specified in `cloudflow.runtimes.[runtime].config` is merged as fallback, streamlet specific configuration takes precedence.
An example is shown below:

[source, hocon]
----
cloudflow {
  runtimes {
    akka {
      config {
        akka.loglevel = "DEBUG"
      }
      kubernetes {
        pods.pod.containers.container {
          // kubernetes container settings go here  
          env = [ 
            {
              name = "JAVA_OPTS"
              value = "-XX:MaxRAMPercentage=40.0 -Djdk.nio.maxCachedBufferSize=1048576"
            }
          ]

          resources {
            requests {
              cpu = 2
              memory = "512M"
            }
            limits {
              memory = "1024M"
            }
          }
        }
      }
    }    
  } 
}
----


== Configuration Paths as Keys
Paths can be used as keys in HOCON, which is shown in the example below:

[source, hocon]
----
cloudflow.streamlets.my-streamlet {
  config-parameters {
    // config parameter values go here  
  }  
  config {
    // runtime settings go here
  }
  kubernetes.pods.pod.containers.container {
    // kubernetes container settings go here  
  }
}
----

An example of only setting an Akka configuration value is shown below:

[source, hocon]
----
cloudflow.streamlets.my-streamlet.config {
  akka { 
    log-level = "DEBUG"  
  }
}
----

Which can be collapsed further as is shown in the example below:

[source, hocon]
----
cloudflow.streamlets.my-streamlet.config.akka.log-level = "DEBUG"  
----

== Configuring a Streamlet using Command Line Arguments

It is also possible to pass configuration values directly as command line arguments, as `[config-path]=value` pairs separated by
a space. The `[config-path]` must be an absolute path to the value, exactly how it would be defined in a config file, using configuration paths. 
Some examples:

[source, bash]
----
$ {cli-plugin} cloudflow deploy target/swiss-knife.json \
  cloudflow.streamlets.akka-process.config.akka.log-level = "DEBUG"
----


[source, bash]
----
$ {cli-plugin} cloudflow deploy target/swiss-knife.json \
  cloudflow.runtimes.spark.config.spark.driver.memoryOverhead=512
----

[source, bash]
----
$ {cli-plugin} cloudflow deploy target/swiss-knife.json \ 
  cloudflow.runtimes.spark.config.spark.driver.memoryOverhead=512 \
  cloudflow.streamlets.spark-process.config-parameters.configurable-message='SPARK-OUTPUT:'
----

The arguments passed with `[config-key]=[value]` pairs take precedence over the files passed through with the `--conf` flags.


== Streamlet Configuration Parameters
Configuration parameters can be used to indicate that a streamlet requires configuration before it is run. 

Examples of configuration parameters are database connection strings, URLs, credentials, or anything else that you want to specify at deployment time.

A streamlet specifies that it requires particular config parameters by expressing them in code. 
The values for these parameters will be requested, validated, and set when `kubectl cloudflow deploy` or `kubectl cloudflow configure` is used to deploy or configure the Cloudflow application.

There are a number of predefined configuration parameter types:

|======
|`IntegerConfigParameter`| A signed 32 bit integer value.
|`StringConfigParameter`| A string with the max length of 1k characters.
|`DoubleConfigParameter`| A 64 bit floating point value.
|`BooleanConfigParameter`| A boolean value.
|`RegExpConfigParameter`| A string validated using a regular expression.
|`DurationConfigParameter`| A duration string, for example "2 minutes".
|`MemorySizeConfigParameter`| A memory size string, for example "32M".
|======

In addition to the predefined types, you can also define your own types.

== Using a configuration parameter in a streamlet

The following section will break down how we can use an `Integer` configuration parameter type in a streamlet to request the value for a maximum number of records within a time window.

[source,scala]
--
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-scala/src/main/scala/cloudflow/akkastreamsdoc/RecordSumFlow.scala[tag=all]
--

As seen in the example below, we first need to create an instance of `IntegerConfigParameter`.

[source,scala]
--
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-scala/src/main/scala/cloudflow/akkastreamsdoc/RecordSumFlow.scala[tag=definition]
--

The arguments provided to `IntegerConfigParameter()` are the following:

    - A key, which has to be unique within the streamlet.
    - Optionally, a description, which will be shown by the CLI.
    - Optionally, a default value, which will be used by the CLI when no value is passed during deploy.

After the configuration parameter is defined, we can use it to extract its value from the runtime configuration in the `createLogic` function:

[source,scala]
--
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-scala/src/main/scala/cloudflow/akkastreamsdoc/RecordSumFlow.scala[tag=usage]
--

Note that its up to the developer to use the correct config method to extract the value of the parameter. Since the type being used here is `IntegerConfigParameter` the config method used is `getInt`.

== Custom validation

It is easy to create your own custom validation for a configuration parameter using the `RegExpConfigParameter` type. This type allows you to validate the entered value using a regular expression.

For example, if we want to validate a 24 hour timestamp, this is how it could be defined and used in a streamlet.

[source,scala]
--
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-scala/src/main/scala/cloudflow/akkastreamsdoc/ConfigCustomValidation.scala[tag=definition]
--

== Providing values for configuration parameters when testing streamlets

When writing tests for streamlets, you can provide values for configuration parameters when you initialize the runner-specific testkit.

If we want to write a test for the example streamlet `RecordSumFlow`, we could add values for the `recordsInWindowParameter` configuration parameter like this:

[source,scala]
--
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-scala/src/test/scala/com/example/SampleSpec.scala[tag=config-value]
--

The Spark testkit has a similar function for adding values to configuration parameters when testing a streamlet.

[source,scala]
--
include::{cloudflow-examples-version}@docsnippets:ROOT:example$spark-scala/src/test/scala/com/example/SampleSpec.scala[tag=config-value]
--

The Java API is slightly different as you can see in the example below:

[source,java]
--
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-java/src/test/java/com/example/SampleTest.java[tag=config-value]
--

== Using configuration parameters in Java

Using the Configuration parameters in Java is similar to the Scala version. The main difference is how class instantiation is done and how to retrieve the config parameter key.

Creating an instance of a `StringConfigParameter` in Java:

[source,java]
--
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-java/src/main/java/cloudflow/akkastreamsdoc/FilterStreamlet.java[tag=definition]
--

Example of accessing the value of a configuration parameter in Java:

[source,java]
----
include::{cloudflow-examples-version}@docsnippets:ROOT:example$akkastreams-java/src/main/java/cloudflow/akkastreamsdoc/FilterStreamlet.java[tag=usage]
----


== Providing configuration parameters when deploying a Cloudflow application

Configuration parameters will need to be provided with values during deployment of the application. The `deploy` command accepts these values as a set of key/value pairs.

The format for specifying configuration parameter values is as follows:

    [config-path]="[value]"

Deploying an application without specifying values for all required configuration parameters will fail and result in an error message like the following.


[source,bash,subs=attributes+]
----
$ {cli-plugin} cloudflow deploy target/call-record-pipeline.json \
  cloudflow.streamlets.cdr-aggregator.config-parameters.group-by-window="7 minute" \ 
  cloudflow.streamlets.cdr-aggregator.config-parameters.watermark="1 minute"

[Error] Please provide values for the following configuration parameter(s):
- cloudflow.streamlets.cdr-generator1.config-parameters.records-per-second - Records per second to process.
- cloudflow.streamlets.cdr-generator2.config-parameters.records-per-second - Records per second to process.
----

To successfully deploy the application, all configuration parameter values have to be provided via a configuration file using `--conf file` or directly on the command line:

[source,bash,subs=attributes+]
----
$ {cli-plugin} cloudflow deploy target/call-record-pipeline.json --conf test-config.conf

[Done] Deployment of application `call-record-aggregator` has started.
----

Configuration parameters can be omitted from the configuration file or the deployment command line as long as they have default values. 
[source,bash,subs=attributes+]
----
$ {cli-plugin} cloudflow deploy target/sensor-data-java.json

Default value 'device-ids.txt' will be used for configuration parameter 'cloudflow.streamlets.filter.config-parameters.filter-filename'
Default value '10' will be used for configuration parameter 'cloudflow.streamlets.filter.config-parameters.filter-pollinginterval'

[Done] Deployment of application `sensor-data-java` has started.
----

== Runtime Settings

Runtime configuration for a specific streamlet can be provided in `cloudflow.streamlets.[streamlet-name].config`.
An example of setting Akka configuration for a `my-streamlet` streamlet is shown below:

[source, hocon]
----
cloudflow.streamlets.my-streamlet.config {
  akka { 
    log-level = "DEBUG"  
  }
}
----

If the blueprint contains more streamlets than just `my-streamlet` as show above, these will use default runtime configuration.
The example below shows how to set the configuration for all Akka streamlets:

[source, hocon]
----
cloudflow.runtimes.akka.config {
  akka { 
    log-level = "INFO"  
  }
}
----

The combined example shown below specifies that by default the `akka.loglevel` setting should be set to `INFO`. 
Specifically for `my-streamlet` the log-level overrides this default and is set to `DEBUG`.

[source, hocon]
----
cloudflow.streamlets.my-streamlet.config {
  akka { 
    log-level = "DEBUG"  
  }
}
cloudflow.runtimes.akka.config {
  akka { 
    log-level = "INFO"  
  }
}
----

Another example shows that you can provide configuration for all the runtimes your application uses, in this case Akka and Spark:
[source, hocon]
----
cloudflow.runtimes.spark.config {
  spark.driver.memoryOverhead=384
}
cloudflow.runtimes.akka.config {
  akka { 
    log-level = "INFO"  
  }
}
----


== Kubernetes Container Settings

Container resource requirements and environment variables can be set in the `cloudflow.streamlets.[streamlet-name].kubernetes` section.
The example below shows how resource requirements are set specifically for a `my-streamlet` streamlet:

[source, hocon]
----
cloudflow.streamlets.my-streamlet {
  kubernetes.pods.pod.containers.container {
    env = [ 
          { name = "JAVA_OPTS" 
            value = "-XX:MaxRAMPercentage=40.0"
          },{
            name = "FOO"
            value = "BAR"
          }
        ]
    resources {
      requests {
        cpu = "500m"
        memory = "512Mi"
      }
      limits {
        memory = "4Gi"
      }
    }
  }
}
----

The above example shows that `500mcpu` is requested, as well as `512Mi` of memory. The pod is limited to use `4Gi` of memory.
It also shows how to set options to the JVM through an environment variable. 
For runtimes that only deploy one pod per streamlet, the config path for the container settings is `kubernetes.pods.pod.containers.container`.
Spark and Flink create two types of pods:

      - Spark creates Driver and Executor pods
      - Flink creates JobManager and TaskManager pods

If you specify Kubernetes container settings via `kubernetes.pods.pod.containers.container`, the same settings will apply for all types of pods.
For Spark you can use the following paths:
  
      - For the Driver pods: `kubernetes.pods.driver.containers.container`      
      - For the Executor pods: `kubernetes.pods.executor.containers.container`      

For Flink you can use the following paths:
  
      - For the JobManager pods: `kubernetes.pods.job-manager.containers.container`      
      - For the TaskManager pods: `kubernetes.pods.task-manager.containers.container`      

You can also specify the Kubernetes container settings for all streamlets using a particular runtime. This is shown in the example below:

[source, hocon]
----
cloudflow.runtimes.spark {
  kubernetes.pods {
    driver.containers.container {
      resources {
        requests {
          cpu = "1"
          memory = "1Gi"
        }
        limits {
          memory = "2Gi"
        }
      }
    }

    executor.containers.container {
      resources {
        requests {
          cpu = "2"
          memory = "2Gi"
        }
        limits {
          memory = "6Gi"
        }
      }
    }
  }
}
----

The above example shows specific container settings for the Spark driver and executor pods. In this case the driver pods will request `1` cpu and `1Gi` of memory, limited to `2Gi` of memory. The executors will be requesting `2` cpus, `2Gi` of memory, limited to `6Gi`.