

include::ROOT:partial$include.adoc[]

To upgrade Cloudflow after a new release use the Helm upgrade command.

== Upgrading

To upgrade Cloudflow in your cluster to the latest version run

[source,shell script]
----
  helm upgrade cloudflow cloudflow-helm-charts/cloudflow \
    --namespace cloudflow \
    --set kafkaClusters.default.bootstrapServers=cloudflow-strimzi-kafka-bootstrap.cloudflow:9092
----

NOTE: Version 2.0.11 introduces the named Kafka clusters feature, which changes how the Kafka bootstrapServers are configured.
When migrating from 2.0.10 to 2.0.11 it is important to not use `--reuse-values` since it clears out values that did not exist in the previous version

== Selecting a specific version

To upgrade Cloudflow to a specific version, add the _--version_ flag. For example:

[source,shell script,subs="attributes"]
----
  helm upgrade cloudflow cloudflow-helm-charts/cloudflow \
    --namespace cloudflow \
    --version="{cloudflow-version}" \
    --set kafkaClusters.default.bootstrapServers=cloudflow-strimzi-kafka-bootstrap.cloudflow:9092
----

Cloudflow 2.0.11 introduces a new setting for the default kafkaClusters, please make sure that this is set to the Kafka bootstrap servers that you currently use, as shown in the above example.

IMPORTANT: A typical upgrade of Cloudflow does not affect the running Cloudflow applications. However, always check the release notes to be sure there are no breaking changes.
