# deployment.yaml

kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloudflow-operator
  labels:
    app.kubernetes.io/version: __cloudflowOperator.imageTag__
    cloudflow.lightbend.com/build-number: __cloudflowOperator.imageTag__
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: __cloudflowOperator.imageTag__
        cloudflow.lightbend.com/build-number: __cloudflowOperator.imageTag__
    spec:
      containers:
        - name: cloudflow-operator
          image: "__cloudflowOperator.imageName__:__cloudflowOperator.imageTag__"
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "cloudflow-kafka-bootstrap.__namespace__:9092"
            - name: KAFKA_STRIMZI_TOPIC_OPERATOR_NAMESPACE
              value: "__namespace__"
            - name: PERSISTENT_STORAGE_CLASS
              value: "__cloudflowOperator.persistentStorageClass__"
