# patch mutatingwebhookconfig

apiVersion: batch/v1
kind: Job
metadata:
  name: cloudflow-patch-spark-mutatingwebhookconfig
spec:
  template:
    spec:
      serviceAccountName: cloudflow-operator
      restartPolicy: OnFailure
      containers:
        - name: main
          image: __webhookPatchJob.image__
          command:
            - bash
            - "-c"
            - |
              apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*
              wget -q -O /bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.12.0/bin/linux/amd64/kubectl && chmod 755 /bin/kubectl
              NAME="cloudflow-sparkoperator"
              API_VERSION=$(kubectl get deployment -n __namespace__ $NAME -o jsonpath='{.apiVersion}')
              UUID=$(kubectl get deployment -n __namespace__ $NAME -o jsonpath='{.metadata.uid}')
              KIND=$(kubectl get deployment -n __namespace__ $NAME -o jsonpath='{.kind}')
              HOOK_NAME="cloudflow-sparkoperator-webhook-config"
              JSON=$(cat <<EOF
              { 
                "metadata": { 
                  "ownerReferences": [ 
                    { 
                      "apiVersion": "$API_VERSION", 
                      "blockOwnerDeletion": true, 
                      "controller": true, 
                      "kind": "$KIND", 
                      "name": "$NAME",
                      "uid": "$UUID" 
                    } 
                  ] 
                } 
              }
              EOF
              )
              echo $JSON
              kubectl patch MutatingWebhookConfiguration $HOOK_NAME -n __namespace__ -p "$JSON"
