# webhook-init-job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: cloudflow-sparkoperator-webhook-init
spec:
  template:
    spec:
      containers:
        - name: main
          image: lightbend/sparkoperator:__sparkOperator.image__
          command:
            [
              "/usr/bin/gencerts.sh",
              "-n",
              "__namespace__",
              "-s",
              "cloudflow-webhook",
              "-p",
            ]
