apiVersion: "akka.lightbend.com/v1"
kind: "AkkaMicroservice"
metadata:
  name: "hello-world"
  namespace: "hello-world"
spec:
  replicas: 1
  image: "docker.io/andreatp/hello-world@sha256:1f6e168d6d5b65e7fa5b9a3d0c5f5b4ad5c66174ab6fd011734f167f03856aef"
  imagePullPolicy: "Always"
  appVersion: "0.0.1"
  livenessProbe:
    exec:
      command:
      - /bin/sh
      - -c
      - cat /tmp/hello-world-live.txt
    initialDelaySeconds: 10
    timeoutSeconds: 1
    periodSeconds: 10
  readinessProbe:
    exec:
      command:
      - /bin/sh
      - -c
      - cat /tmp/hello-world-ready.txt
    initialDelaySeconds: 10
    timeoutSeconds: 1
    periodSeconds: 10
  javaOptions: "-Dconfig.file=/etc/cloudflow-runner-secret/application.conf"
  extraVolumeMounts:
  - name: downward-api-volume
    mountPath: /mnt/downward-api-volume
  secretVolumes:
  - secretName: "hello-world"
    mountPath: "/etc/cloudflow-runner-secret"
  podTemplateSpec:
    spec:
      volumes:
      - name: downward-api-volume
        downwardAPI:
          items:
          - path: metadata.uid
            fieldRef:
              fieldPath: metadata.uid
          - path: metadata.name
            fieldRef:
              fieldPath: metadata.name
          - path: metadata.namespace
            fieldRef:
              fieldPath: metadata.namespace
