= Cloudflow -- streaming data pipelines on Kubernetes
:page-layout: home
:description: Quickly develop, orchestrate, and operate distributed streaming data pipelines with Apache Spark, Apache Flink, and Akka Streams on Kubernetes
:keywords: spark, kubernetes, stream, streaming, stream processing, apache spark, apache flink, akka, akka streams, akka-streams, pipelines, streaming pipelines, streaming pipelines on kubernetes, developer, streaming applications

Cloudflow enables you to quickly develop, orchestrate, and operate distributed streaming applications on Kubernetes. 
With Cloudflow, streaming applications are comprised of small composable components wired together with schema-based contracts. 
Cloudflow can dramatically accelerate streaming application development--reducing the time required to create, package, and deploy--from weeks to hours. 

With its powerful abstractions, Cloudflow allows you to easily define the most complex streaming applications:

* Develop: Focus only on business logic, leave the boilerplate to us.
* Build: We provide all the tooling for going from business logic to a deployable Docker image.
* Deploy: We provide Kubernetes tooling to deploy your distributed system with a single command, and manage durable connections between processing stages.
* Operate: With a Lightbend subscription, you get all the tools you need to provide insights, observability, and lifecycle management for evolving your distributed streaming application.


Cloudflow integrates with popular streaming engines like Akka, Spark and Flink. It also comes with a powerful CLI tool to easily manage, scale and configure streaming applications at runtime. In a nutshell, Cloudflow is an application development toolkit composed of:

* An API definition for `Streamlet`, the core abstraction in Cloudflow.
* An extensible set of runtime implementations for `Streamlet`(s). Cloudflow provides support for popular streaming runtimes, like Spark's Structured Streaming, Flink, and Akka.
* A `Streamlet` composition model driven by a `blueprint` definition.
* A sandbox execution mode that accelerates the development and testing of your applications.
* A set of `sbt` plugins that are able to package your application into a deployable container.
* The Cloudflow operator, a Kubernetes operator that manages the application lifecycle on Kubernetes.
* A CLI, in the form of a `kubectl plugin`, that facilitates manual and scripted management of the application.

== Where To Go Next?
* link:./docs/current/get-started/index.html[Getting Started with Cloudflow]
* link:./docs/current/develop/cloudflow-streamlets.html[Developing Applications with Cloudflow]
* https://github.com/lightbend/cloudflow/blob/master/installer/README.md[Setup Cloudflow on a Kubernetes Cluster]
* Chat with us on https://gitter.im/lightbend/cloudflow[Gitter]
* Ask us a question on https://discuss.lightbend.com/c/cloudflow[Discuss]
* Want to https://github.com/lightbend/cloudflow/blob/master/CONTRIBUTING.md[contribute]?
