apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume
  namespace: sensor-data-scala
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi