= Develop example streamlets
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::ROOT:partial$include.adoc[]

All streamlets belong under the `src/main/scala/sensordata` directory, where `sensordata` is the package name. To develop the streamlets, copy the provided code to the appropriate source file name. The complete code is available in the https://github.com/lightbend/cloudflow/tree/master/examples/sensor-data-scala[sensor-data-scala] example.

== Ingress streamlet

Let's start with the ingress, which we implement in a class named `SensorDataHttpIngress`. The ingress has an outlet through which ingested data is passed downstream through the pipeline. In any streamlet class, the `StreamletLogic` abstracts the behavior and we use the default behavior that `HttpServerLogic` offers out of the box. 

In **SensorDataHttpIngress.scala**, include the following code:

[source,scala]
----
include::ROOT:example$sensor-data-scala/src/main/scala/sensordata/SensorDataHttpIngress.scala[]
----

== Convert sensor to metric streamlet

We will have the ingress pass data to another streamlet, `SensorDataToMetrics`. This streamlet has an inlet and an outlet and processes data that it receives using the business logic. In this example we convert objects of type `SensorData` to domain `Metric` objects - note that the inlets and outlets are typed accordingly.

In **SensorDataToMetrics.scala**, include the following code:

[source,scala]
----
include::ROOT:example$sensor-data-scala/src/main/scala/sensordata/SensorDataToMetrics.scala[]
----

== Validation streamlets

Now that we have the metric that we would like to measure and track, we need to validate them using business rules. And we have a separate `MetricValidation` streamlet for doing exactly this.

This streamlet has an inlet and 2 outlets for generating valid and invalid metrics. And all of them are typed based on the data that they are expected to handle. In the behavior handled by `createLogic` method, `SensorDataUtils.isValidMetric(..)` handles the business validation. We implement that logic in the next class.

In **MetricsValidation.scala**, include the following code:

[source,scala]
----
include::ROOT:example$sensor-data-scala/src/main/scala/sensordata/MetricsValidation.scala[]
----

In **SensorDataUtils.scala**, include the following code. A real validator would have more complex business logic, this is just for demonstration:

[source,scala]
----
include::ROOT:example$sensor-data-scala/src/main/scala/sensordata/package.scala[]
----

== Logging streamlets

Next, we want to log the valid and invalid metrics separately in 2 streamlets - `valid-logger` nd `invalid-logger`.


In **ValidMetricLogger.scala**, include the following code:

[source,scala]
----
include::ROOT:example$sensor-data-scala/src/main/scala/sensordata/ValidMetricLogger.scala[]
----


In **InvalidMetricLogger.scala**, include the following code:

[source,scala]
----
include::ROOT:example$sensor-data-scala/src/main/scala/sensordata/InvalidMetricLogger.scala[]
----

== Process JSON records

Finally we have some support classes that we need to process JSON records through the Cloudflow pipeline. 

In **JsonFormats.scala**, include the following code:


[source,scala]
----
include::ROOT:example$sensor-data-scala/src/main/scala/sensordata/JsonFormats.scala[]
----


In **package.scala**, include the following code:

[source,scala]
----
include::ROOT:example$sensor-data-scala/src/main/scala/package.scala[]
----

== What's next

With the schema and streamlets ready, we need to wire the streamlet flow together by xref:create-example-blueprint.adoc[creating the example blueprint].
