site:
  title: "Cloudflow Guide"
  url: https://cloudflow.io
content:
  sources:
    - url: git@github.com:lightbend/cloudflow.git
      start-paths:
        - docs/docs-source/docs
        - docs/shared-content-source/docs
        - examples/snippets
      branches: [v1.3.3-docs, v2.0.0-docs, v2.0.25-docs, v2.1.0-docs, v2.1.2-docs, v2.2.0-docs, v2.2.2-docs, v2.3.0-docs, v2.3.1-docs, v2.3.2-docs] # versioned content - add branches here
    - url: git@github.com:lightbend/cloudflow.git
      start-path: docs/homepage-source/docs
      branches: [main] # should always remain as main
ui:
  bundle:
    url: https://lightbend.github.io/antora-supplemental-ui-lightbend-theme/default_ui/ui-bundle-756539289.zip
    snapshot: true
  default_layout: default
  supplemental_files: ./supplemental_ui
runtime:
  fetch: true
asciidoc:
  attributes:
    # the following two attributes cause review and todo notes to display
    # review: ''
    # todo: ''
    doc-title: 'Cloudflow Guide'
    oss: ''
output:
  dir: ./../target/staging
  clean: true
