site:
  title: "Cloudflow Guide"
  url: https://cloudflow.io
content:
  sources:
    - url: git@github.com:lightbend/cloudflow.git
      start-paths:
        - docs/docs-source/docs
        - docs/shared-content-source/docs
        - examples/snippets
      # TODO: check if we can restore all the versions
      # branches: [master, v1.3.3-docs, v2.0.0-docs, v2.0.5-docs, v2.0.7-docs, v2.0.8-docs, v2.0.10-docs, v2.0.11-docs, v2.0.12-docs, v2.0.13-docs, v2.0.14-docs, v2.0.16-docs, v2.0.18-docs, v2.0.19-docs, v2.0.20-docs, v2.0.21-docs] # versioned content - add branches here
      branches: [v1.3.3-docs, v2.0.0-docs, v2.0.18-docs, v2.0.19-docs, v2.0.20-docs, v2.0.21-docs, v2.0.22-docs, v2.0.23-docs, v2.0.24-docs] # versioned content - add branches here
    - url: git@github.com:lightbend/cloudflow.git
      start-path: docs/homepage-source/docs
      branches: [master] # should always remain as master
ui:
  bundle:
    url: https://lightbend.github.io/antora-supplemental-ui-lightbend-theme/default_ui/ui-bundle-756539289.zip
    snapshot: true
  default_layout: default
  supplemental_files: ./supplemental_ui
runtime:
  fetch: true
asciidoc:
  attributes:
    # the following two attributes cause review and todo notes to display
    # review: ''
    # todo: ''
    doc-title: 'Cloudflow Guide'
    oss: ''
output:
  dir: ./../target/staging
  clean: true
