site:
  title: "Cloudflow Guide"
  url: https://cloudflow.io 
  
content:
  sources:
  - url: git@github.com:lightbend/cloudflow.git
    start-paths: 
      - docs/docs-source/docs
      - docs/shared-content-source/docs
      - examples/snippets
    branches: [master, v1.3.3-docs, v2.0.0-docs, v2.0.5-docs, v2.0.7-docs, v2.0.8-docs]  # versioned content - add branches here 
  - url: git@github.com:lightbend/cloudflow.git
    start-path: docs/homepage-source/docs
    branches: [master] # should always remain as master

ui: 
  bundle:
    url: https://github.com/lightbend/antora-ui-lightbend-cloud-theme/raw/master/build/ui-bundle.zip
    snapshot: true
    
runtime:
  fetch: true

asciidoc:

  attributes:
    # the following two attributes cause review and todo notes to display
    # review: ''
    # todo: ''
    doc-title: 'Cloudflow Guide'

output:
   dir: ./../target/staging
   clean: true
