# serviceaccount.yaml

kind: ServiceAccount
apiVersion: v1
metadata:
  name: cloudflow-operator
  labels:
    app.kubernetes.io/version: __cloudflowOperator.imageTag__
    cloudflow.lightbend.com/build-number: __cloudflowOperator.imageTag__
automountServiceAccountToken: true