# strimzi-kafka-cluster.yaml

apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cloudflow
  namespace: __namespace__
  labels:
    app.kubernetes.io/version: __cloudflowOperator.imageTag__
    cloudflow.lightbend.com/build-number: __cloudflowOperator.imageTag__
spec:

  kafka:
    image: __kafka.imageName__:__kafka.imageTag__
    tlsSidecar:
      image: __kafka.imageName__:__kafka.imageTag__
    resources:
      requests:
        cpu: 500m
        memory: 2G
    storage:
      type: persistent-claim
      class: __kafkaClusterCr.kafkaPersistentStorageClass__

  zookeeper:
    image: __kafka.imageName__:__kafka.imageTag__
    tlsSidecar:
      image: __kafka.imageName__:__kafka.imageTag__
    resources:
      requests:
        cpu: 500m
        memory: 2G
    storage:
      type: persistent-claim
      class: __kafkaClusterCr.zookeeperPersistentStorageClass__

  entityOperator:
    topicOperator:
      image: __strimziOperator.imageName__:__strimziOperator.imageTag__
    userOperator:
      image: __strimziOperator.imageName__:__strimziOperator.imageTag__
    tlsSidecar:
      image: __kafka.imageName__:__kafka.imageTag__

  cruiseControl:
    image: __kafka.imageName__:__kafka.imageTag__
    tlsSidecar:
      image: __kafka.imageName__:__kafka.imageTag__

  jmxTrans:
    image: __kafka.imageName__:__kafka.imageTag__
