= Define Avro schema


include::ROOT:partial$include.adoc[]

Let's start building the avro schema for the domain objects that we need for the application. 
These schema files have the extension `.avsc` and go directly under `src/main/avro` in the project structure that we discussed earlier.

When using Avro for serialization of domain objects (and reading/writing them from/to Kafka), it is necessary to add a dependency to the `cloudflow-avro` library:
- add libraryDependendy `Cloudflow.library.CloudflowAvro` (in SBT)
- or explicitly add the dependency to `"com.lightbend.cloudflow" %% "cloudflow-avro" % <Cloudflow.Version>` (in any build tool)

It is also possible to use Protobuf instead of Avro.
In this instance, the `cloudflow-protobuf` dependency needs to be added to the project:
- add libraryDependendy `Cloudflow.library.CloudflowProto` (in SBT)
- or explicitly add the dependency to `"com.lightbend.cloudflow" %% "cloudflow-proto" % <Cloudflow.Version>` (in any build tool)


In the Wind Turbine example, we will use the following domain objects:

* **SensorData:** The data that we receive from the source and ingest through our ingress.
* **Measurements:** A substructure of `SensorData` that abstracts the values of interest, such as wind speed.
* **Metric:** A domain object that identifies the reported values we would like to track and measure.
* **InvalidMetric:** An object that encapsulates the erroneous metric.

During the build process, the Cloudflow plugin system processes the schemas. 
For each of these schema files, Cloudflow will generate Scala case classes that can be directly used from within the application.

NOTE: Full sources for all Cloudflow example applications can be found in the
https://github.com/lightbend/cloudflow/tree/main/examples/snippets/modules/ROOT/examples[examples folder] of the
https://github.com/lightbend/cloudflow[`cloudflow` project on Github].
The sources for the example described below can be found in the application called
https://github.com/lightbend/cloudflow/tree/main/examples/snippets/modules/ROOT/examples/sensor-data-scala[sensor-data-scala].


== Creating the schema files

To create the avro schema for the domain objects, follow these steps:

. Create a `SensorData.avsc` file and save it in the `avro` subdirectory of the example project. Use the following definition:
+
[source,json]
----
include::{cloudflow-examples-version}@docsnippets:ROOT:example$sensor-data-scala/src/main/avro/SensorData.avsc[]
----

. Create a `Measurements.avsc` file and save it in the `avro` subdirectory of the example project. Use the following definition: 
+
[source,json]
----
include::{cloudflow-examples-version}@docsnippets:ROOT:example$sensor-data-scala/src/main/avro/Measurements.avsc[]
----


. Create a `Metric.avsc` file and save it in the `avro` subdirectory of the example project. Use the following definition: 
+
[source,json]
----
include::{cloudflow-examples-version}@docsnippets:ROOT:example$sensor-data-scala/src/main/avro/Metric.avsc[]
----

. Create an `InvalidMetric.avsc` file and save it in the `avro` subdirectory of the example project. Use the following definition:
+
[source,json]
----
include::{cloudflow-examples-version}@docsnippets:ROOT:example$sensor-data-scala/src/main/avro/InvalidMetric.avsc[]
----

== What's next

Now we can xref:develop-example-streamlets.adoc[develop the Wind Turbine example streamlets].
