= How to install Strimzi and create a Kafka cluster
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2

include::ROOT:partial$include.adoc[]

This document shows how to install Strimzi and create a Kafka cluster suitable for use with Cloudflow.

== Prerequisites

=== CLI Tools

Make sure you have the following prerequisites installed before continuing:

- Helm, version 3 or later
- Kubectl 

== Installing Strimzi

Strimzi can be installed using Helm. 


== Creating a Kafka cluster using Strimzi

To create a Kafka cluster using Strimzi we have to create a `CustomResource` of the kind `Kafka` in the namespace `cloudflow`. Creating the resource in the right namespace is important since we told Strimzi to only watch the `cloudflow` namespace when installing.

Create the file using the following snippet.

----
cat > kafka-cluster.yaml << EOF
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cloudflow-strimzi
  namespace: cloudflow
spec:
  entityOperator:
    topicOperator:
      resources: {}
  kafka:
    config:
      auto.create.topics.enable: false
      log.message.format.version: "2.3"
      log.retention.bytes: 112197632
      log.retention.hours: -1
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      plain: {}
      tls: {}
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 3
    resources: {}
    storage:
      deleteClaim: false
      size: 1Gi
      type: persistent-claim
    version: 2.4.0
  zookeeper:
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 3
    resources: {}
    storage:
      deleteClaim: false
      size: 1Gi
      type: persistent-claim
EOF
----

Apply the yaml file with the Kafka custom resource to the cluster:

  kubectl apply -f kafka-cluster.yaml

TIP: If you want to change any parameters of the Kafka cluster, just edit the `kafka-cluster.yaml` file and apply it again to the cluster as shown above. The Strimzi Kafka cluster operator will make the necessary changes when it detects a change in the custom resource.

== Removing Strimzi 

If you want to remove Strimzi, you can do that with the following Helm command.

  helm delete strimzi -n cloudflow

