:page-partial:

include::ROOT:partial$include.adoc[]

To develop and deploy Cloudflow applications, you will need a Java SDK (JDK), Docker, a Kubernetes cluster, the `sbt` build tool, and the Cloudflow CLI, which is an extension for `kubectl`. 

ifdef::oss[This page describes the required environment to prepare for development. Please see xref:administration:installing-cloudflow.adoc[Installing Cloudflow] for instructions on how to install Cloudflow on a Kubernetes cluster.]


== Prerequisites

First, make sure that you have the following installed:

* Java(JDK) {supported-java-v}
* https://www.scala-sbt.org/[sbt,window=_blank], {supported-sbt-v}
* https://www.docker.com/community-edition[Docker,window=_blank], {supported-docker-v}
* https://helm.sh/docs/intro/install/[Helm,window=_blank], {supported-helm-v}. We recommend version 3 to avoid dealing with tiller.
* https://kubernetes.io/docs/tasks/tools/install-kubectl/[kubectl,window=_blank]

NOTE: The default build tool for Cloudflow applications is `sbt` but there is support for using xref:docs:develop:maven-support.adoc[Maven] to build as well.

== Download and install the Cloudflow CLI

Install the Cloudflow CLI using the official installer:

....
curl -sL http://cloudflow.io/docs/get.sh | bash
....

You can pass options to the installer script with `-s --` e.g.:

....
curl -sL http://cloudflow.io/docs/get.sh | bash -s -- --prefix=$HOME --version=2.0.22 --verbose
curl -sL http://cloudflow.io/docs/get.sh | bash -s -- -P $HOME -v 2.0.22 -V
....

If the installer script fails, please, report the failure and download the binaries at the specific version at the url:

* https://repo.lightbend.com/raw/cloudflow-cli/versions/<version>/kubectl-cloudflow-<version>-<platform>-amd64.tar.gz

where you have to substitute:

  - <version> with the specific version (e.g. `2.0.23`)
  - <platform> with one of `darwin`, `linux`, `windows` depending on the target OS

ifdef::review[Reviewers:still need recommendations for Windows.]
