apiVersion: v1
data:
  secret.conf: Ym9vdHN0cmFwLnNlcnZlcnMgPSAiY2xvdWRmbG93LXN0cmltemkta2Fma2EtYm9vdHN0cmFwLmNsb3VkZmxvdzo5MDkyIgpwYXJ0aXRpb25zID0gNTMKcmVwbGljYXMgPSAyCmNvbm5lY3Rpb24tY29uZmlnID0gewp9CnByb2R1Y2VyLWNvbmZpZyA9IHsKfQpjb25zdW1lci1jb25maWcgPSB7Cn0K
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: cloudflow
    meta.helm.sh/release-namespace: cloudflow
  labels:
    app.kubernetes.io/version: 2.0.24
    cloudflow.lightbend.com/build-number: 2.0.24
    cloudflow.lightbend.com/kafka-cluster-name: default
    cloudflow.lightbend.com/release-version: 2.0.24
  name: cloudflow-kafka-cluster-default
  namespace: cloudflow
type: Opaque
