apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
  namespace: tensorflow-akka
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
