apiVersion: v1
kind: Namespace
metadata:
  name: cloudflow
  ownerReferences:
  - blockOwnerDeletion: true
    controller: true
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: cloudflows.cloudflow-installer.lightbend.com
    uid: CLOUDFLOW_CRD_UID_PH
---
apiVersion: cloudflow-installer.lightbend.com/v1alpha1
kind: Cloudflow
metadata:
  generation: 1
  labels:
    app.kubernetes.io/managed-by: cloudflow-installer
  name: default
  namespace: cloudflow
spec:
  flink_operator:
    version: 0.8.2
    service_account: cloudflow-operator
    image_name: CLOUDFLOW_FLINK_OPERATOR_IMAGE_NAME_PH
    image_tag: CLOUDFLOW_FLINK_OPERATOR_IMAGE_TAG_PH
  spark_operator:
    version: 0.6.7
    image_name: CLOUDFLOW_SPARK_OPERATOR_IMAGE_NAME_PH
    image_tag: CLOUDFLOW_SPARK_OPERATOR_IMAGE_TAG_PH
    webhook_patch_job_image: WEBHOOK_PATCH_JOB_IMAGE_PH
  kafka_cluster_cr:
    name: strimzi
    zoo_keeper_persistent_storage_class: RWO_STORAGE_CLASS_PH
    version: 0.16.2
    kafka_persistent_storage_class: RWO_STORAGE_CLASS_PH
    kafka_image_name: KAFKA_IMAGE_NAME_PH
    kafka_image_tag: KAFKA_IMAGE_TAG_PH
    strimzi_operator_image_name: STRIMZI_OPERATOR_IMAGE_NAME_PH
    strimzi_operator_image_tag: STRIMZI_OPERATOR_IMAGE_TAG_PH
  cloudflow_operator:
    image_name: CLOUDFLOW_OPERATOR_IMAGE_NAME_PH
    image_tag: CLOUDFLOW_OPERATOR_IMAGE_TAG_PH
    persistent_storage_class: RWM_STORAGE_CLASS_PH
