apiVersion: v1
kind: Namespace
metadata:
  name: cloudflow-installer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cloudflow-installer
  name: cloudflow-installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: cloudflow-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cloudflow-installer
    namespace: cloudflow-installer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflow-installer-deployment
  namespace: cloudflow-installer
  labels:
    app: cloudflow-installer
spec:
  selector:
    matchLabels:
      app: cloudflow-installer
  template:
    metadata:
      labels:
        app: cloudflow-installer
    spec:
      serviceAccountName: cloudflow-installer
      containers:
        - name: cloudflow-installer
          image: lightbend/cloudflow-installer:CLOUDFLOW_INSTALLER_IMAGE_TAG_PH
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /checks/ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /checks/healthy
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
