# flink-rbac.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-role-binding
subjects:
- kind: ServiceAccount
  name: __flinkOperator.serviceAccount__
  namespace: default