kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloudflow-flink-operator
spec:
  template:
    spec:
      containers:
        - name: flinkoperator-gojson
          image: __flinkOperator.imageName__:__flinkOperator.imageTag__
          resources:
            limits:
              cpu:     "2"
              memory:  1G
            requests:
              cpu:     500m
              memory:  1G
