apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-efs
  namespace: sensor-data-java
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 1Gi
