tags:
  targetGke: true
  targetMinikube: false
  targetMinishift: false


defaultPersistentStorageClass: gke-ssd

kafka:
  strimzi:
    kafka:
     persistentVolumeClaimSize: 100Gi
     persistentStorageClass: gke-ssd
     resources:
        requests:
          memory: "5Gi"
        limits:
          memory: "9Gi"
    zookeeper:
      persistentVolumeClaimSize: 10Gi
      persistentStorageClass: gke-ssd
      resources:
        requests:
          memory: "1Gi"
        limits:
          memory: "3Gi"


operator:
  clusterType: "gke"
  akkaRunner:
    requestsMemory: "128M"
    requestsCpu: "0.5"
    limitsMemory: "2048M"
  sparkDriver:
    requestsCpu: "0.5"
    requestsMemory: "1024M"
  sparkExecutor:
    requestsCpu: "1"
    requestsMemory: "2G"
  persistentStorageClass: "nfs"
