# https://github.com/actions/labeler
name: "Pull Request Labeler"
on:
  - pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
