# This is useful for when you want to see all non-filtered, non-formatted JMX metrics.
# Must be defined for the appropriate runner (in place of any other rules files) in `Settings.scala`
lowercaseOutputName: true
attrNameSnakeCase: true
rules:
  # Kafka Consumer lag and throughput, Kafka Producer throughput metrics
  # regex testing: https://regex101.com/r/ihtmzH/2
  - pattern: kafka\.consumer<type=consumer-fetch-manager-metrics,\s*client-id=(\S+),\s*topic=(\S+),\s*partition=([0-9]+).*><>records-lag-max
    name: kafka_consumer_consumer_fetch_manager_metrics_records_lag_max
    type: GAUGE
    labels:
      client_id: "$1"
      topic: "$2"
      partition: "$3"
  - pattern: kafka\.consumer<type=consumer-fetch-manager-metrics,\s*client-id=(\S+),\s*topic=(\S+),\s*partition=([0-9]+).*><>records-lag
    name: kafka_consumer_consumer_fetch_manager_metrics_records_lag
    type: GAUGE
    labels:
      client_id: "$1"
      topic: "$2"
      partition: "$3"
  - pattern: kafka\.consumer<type=consumer-fetch-manager-metrics,\s*client-id=(\S+),\s*topic=(\S+).*><>records-consumed-rate
    name: kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate
    type: GAUGE
    labels:
      client_id: "$1"
      topic: "$2"
  - pattern: kafka\.producer<type=producer-topic-metrics,\s*client-id=(\S+),\s*topic=(\S+).*><>record-send-rate
    name: kafka_producer_producer_metrics_record_send_rate
    type: GAUGE
    labels:
      client_id: "$1"
      topic: "$2"
  ## Job Manager
  # Example: org.apache.flink.jobmanager.job.lastCheckpointSize<host=taxi-ride-fare-seglo-processor-dde77c7d, job_name=Executing_processor, job_id=0fe996c92fdc3050341a368a249c47a2><>Value
  # https://regex101.com/r/vNDwzC/4
  - pattern: org.apache.flink.jobmanager.job.(.*)<host=(.*), job_name=(.*), job_id=(.*)><>Value
    name: flink_jobmanager_job_$1
    labels:
      host: $2
      job_name: $3
      job_id: $4

  # Example: org.apache.flink.jobmanager.taskSlotsTotal<host=taxi-ride-fare-seglo-processor-dde77c7d><>Value
  # https://regex101.com/r/vNDwzC/5
  - pattern: org.apache.flink.jobmanager.(.*)<host=(.*)><>Value
    name: flink_jobmanager_$1
    labels:
      host: $2

  ## Task Manager
  # Example: org.apache.flink.taskmanager.job.task.numBytesInLocalPerSecond<task_name=Source-_Custom_Source, job_id=96074949e662720c580972dca7dffc41, task_attempt_id=8ad2c540456bbc1a28c0e4fe1d291c02, job_name=Executing_processor, tm_id=424245a31823afcebbc0b45594394da1, task_id=feca28aff5a3958840bee985ee7de4d3, task_attempt_num=0, host=taxi-ride-fare-seglo-processor-dde77c7d-tm-5698bb9bbf-zb4qj, subtask_index=2><>Count
  # https://regex101.com/r/vNDwzC/2
  - pattern: org.apache.flink.taskmanager.job.task.(.*)<task_name=(.*), job_id=(.*), task_attempt_id=(.*), job_name=(.*), tm_id=(.*), task_id=(.*), task_attempt_num=(.*), host=(.*), subtask_index=(.*)><>Count
    name: flink_taskmanager_$1_total
    labels:
      task_name: $2
      job_id: $3
      task_attempt_id: $4
      job_name: $5
      tm_id: $6
      task_id: $7
      task_attempt_num: $8
      host: $9
      subtask_index: $10
    type: COUNTER

  # Example: org.apache.flink.taskmanager.job.task.currentInputWatermark<task_name=Co-Flat_Map_-_Sink-_Unnamed, job_id=96074949e662720c580972dca7dffc41, task_attempt_id=8f409fbc9a0b71fd4ed27ee944383784, job_name=Executing_processor, tm_id=424245a31823afcebbc0b45594394da1, task_id=685fa031c53f27eb72e36aade80e27bb, task_attempt_num=0, host=taxi-ride-fare-seglo-processor-dde77c7d-tm-5698bb9bbf-zb4qj, subtask_index=3><>Value
  # https://regex101.com/r/vNDwzC/3
  - pattern: org.apache.flink.taskmanager.job.task.(.*)<task_name=(.*), job_id=(.*), task_attempt_id=(.*), job_name=(.*), tm_id=(.*), task_id=(.*), task_attempt_num=(.*), host=(.*), subtask_index=(.*)><>Value
    name: flink_taskmanager_$1
    labels:
      task_name: $2
      job_id: $3
      task_attempt_id: $4
      job_name: $5
      tm_id: $6
      task_id: $7
      task_attempt_num: $8
      host: $9
      subtask_index: $10
