kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistence-data-mount
spec:
  storageClassName: glusterfs-storage
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Gi"